version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
  build:
    commands:
      - echo Build started...
      - ng build --prod
artifacts:
  files:
    - dist/**/*
