version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
      - npm install node
      - npm --version
      - npm install typescript@3.5.3
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
  build:
    commands:
      - echo Build started...
      - ng build --prod --optimization=false 
artifacts:
  files:
     - dist/**/*
    
