version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash . ~/.nvm/nvm.sh
      - nvm install node
      - node --version
      - npm install ng-common
      - npm --version
      - npm install typescript@3.5.3
      - npm install -g @angular/cli
      - npm install --save-dev @angular-devkit/build-angular
      - npm audit fix
  build:
    commands:
      - echo Build started...
      - ng build --prod
artifacts:
  files:
    - dist/**/*
